src/AppBundle/Form/ProfileType.php
<?php

/*
 * This file is part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Form;

use FOS\UserBundle\Util\LegacyFormHelper;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Validator\Constraints\UserPassword;

class ProfileType extends AbstractType
{
   

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->buildUserForm($builder, $options);

        $constraintsOptions = array(
            'message' => 'fos_user.current_password.invalid',
        );

        if (!empty($options['validation_groups'])) {
            $constraintsOptions['groups'] = array(reset($options['validation_groups']));
        }

        $builder->add('current_password', LegacyFormHelper::getType('Symfony\Component\Form\Extension\Core\Type\PasswordType'), array(
            'label' => 'form.current_password',
            'translation_domain' => 'FOSUserBundle',
            'mapped' => false,
            'constraints' => new UserPassword($constraintsOptions),
        ));
    }

 

    // BC for SF < 3.0
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'fos_user_profile';
    }

    /**
     * Builds the embedded form representing the user.
     *
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    protected function buildUserForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', 
                    null, 
                    array(
                        'label' => 'form.username', 
                        'translation_domain' => 'FOSUserBundle',
                        'required' => FALSE ))
            ->add('email', 
                    LegacyFormHelper::getType('Symfony\Component\Form\Extension\Core\Type\EmailType'), 
                    array(
                        'label' => 'form.email', 
                        'translation_domain' => 'FOSUserBundle',
                        'required' => FALSE ))
            
            ->add('current_password', LegacyFormHelper::getType('Symfony\Component\Form\Extension\Core\Type\PasswordType'), array(
            'label' => 'Mot de passe actuelle',
            'translation_domain' => 'FOSUserBundle',
            'required' => FALSE    
 
            
        ))
                
            ->add('gender', 
                    \Symfony\Component\Form\Extension\Core\Type\TextType::class,
                    array(
                        'label' => 'Civilite'
            )) 
            
            ->add('firstname', 
                    \Symfony\Component\Form\Extension\Core\Type\TextType::class,
                    array(
                        'label' => 'Nom'
                    )) 
            ->add('lastname', 
                    \Symfony\Component\Form\Extension\Core\Type\TextType::class,
                    array(
                        'label' => 'Prenom'
                    )) 
            ->add('city', 
                    \Symfony\Component\Form\Extension\Core\Type\TextType::class,
                    array(
                        'label' => 'Ville'
                    )) 
            ->add('zip', 
                    \Symfony\Component\Form\Extension\Core\Type\TextType::class,
                    array(
                        'label' => 'Code Postal'
                    )) 
                        
            ->add('birthdate',
            \Symfony\Component\Form\Extension\Core\Type\DateType::class,
                    array(
                        'label' => 'Date de naissance',
                        'widget' => 'single_text',
                        
                        'html5' => false,
                        'attr' => ['class' => 'js-datepicker'],
                    ))
            
            ->add('address',
            \Symfony\Component\Form\Extension\Core\Type\TextType::class,
                    array(
                        'label' => 'Adresse'
                    ))
            ->add('photo',
            \Symfony\Component\Form\Extension\Core\Type\FileType::class,
                    array(
                        'label' => 'photo',
                        'required' => FALSE
                    ))
                
            ->add('company',
            \Symfony\Component\Form\Extension\Core\Type\TextType::class,
                    array(
                        'label' => 'Société',
                        'required' => FALSE
                    ))
                
            ->add('commercialRegistry',
            \Symfony\Component\Form\Extension\Core\Type\TextType::class,
                    array(
                        'label' => 'Siret',
                        'required' => FALSE
                    ))
                
        
        ;
    }
    
    
    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }
}

src/AppBundle/Controller/User/PreferenceController.php
<?php

namespace AppBundle\Controller\User;

use AppBundle\Entity\Hobby;
use AppBundle\Form\HobbyType;
use PDOException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


class PreferenceController extends Controller
{
    /**
     * 
     * @Route("preference/list")
     */
    public function listAction(Request $request)
    {
        //getting user's ID
        $user = $this->getUser()->getId();
        
        //relation DB
        $em = $this->getDoctrine()->getManager();

        if (is_null($user)) { //page 404 if user not in DB
            throw $this->createNotFoundException();
        }
        
        //access to the Preference Class repository (i.e. Hobby) and display them in the view
        $repository = $em->getRepository('AppBundle:Hobby');
        //request to DB => "SELECT * FROM..."
        $preferences = $repository->findByUser($user);
        
        $form = $this->createForm(HobbyType::class);
        $form->handleRequest($request);
        
        return $this->render(
            'AppBundle:User\Preference:list.html.twig', 
            [
                'preferences'   => $preferences,
                'form'  =>  $form->createView(),
            ]
        );
    }
    
     /**
     * @param Request $request
     * @Route("preference/add")
     */
    public function addAction(Request $request)
    {
        //getting user's ID
        $user = $this->getUser()->getId();
        
        $em = $this->getDoctrine()->getManager();
        
        if (is_null($user)) { //page 404 if user not in DB
            throw $this->createNotFoundException();
        }

        $preference = new Hobby();

        $form = $this->createForm(HobbyType::class, $preference);
        $form->handleRequest($request);
        
        // if the form has been submitted
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $preference
                    ->setUser($this->getUser())
                ;
                
                try {
                    $em->persist($preference);
                    $em->flush();
                } catch (\Doctrine\DBAL\Exception\UniqueConstraintViolationException $exc) {
//                    die ('Oops !'. $exc->getMessage());
                    $this->addFlash('error', 'Vous avez déjà choisi cette categorie.');
                
                return $this->redirectToRoute('app_user_preference_list');
                }

                $em->persist($preference);
                $em->flush();
                
                $this->addFlash('success', 'Votre hobby a été ajouté à votre profil.');
                
                return $this->redirectToRoute('app_user_preference_list');
            } else {
                $this->addFlash('error', 'Les données soumises ne sont pas valides.');
            }
        }
//        $response = new Response();
//        return $response('test');

        return $this->render(
            'AppBundle:User\Preference:add.html.twig', array
            (
                
        ));
    }

    /**
     * @Route("preference/delete/{id}")
     */
    public function deleteAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        
        $preference = $em->find('AppBundle:Hobby', $id);
        
        if (is_null($preference)) { // if no hobby corresponding with the id requested : redirection to the preferences' list
            return $this->redirectToRoute('app_user_preference_list');
        }

        $em->remove($preference);
        $em->flush();
        
        $this->addFlash('success', 'Votre sélection a bien été supprimée.');
        
        return $this->redirectToRoute('app_user_preference_list');
//return $this->render('AppBundle:User\Preference:delete.html.twig', array(
            // ...
//        ));
    }

    // Action set aside for now 
       /**
     * @Route("preference/edit")
     */
    public function editAction()
    {
      return $this->render(
            'AppBundle:User\Preference:edit.html.twig', array
            (
                //...
        ));
    }

//        $em = $this->getDoctrine()->getManager();
    
//         $repository = $em->getRepository('AppBundle:Hobby');
        //request to DB => "SELECT * FROM..."
//        $preferences = $repository->findByUser($user);
        
//        if (is_null($id)) //create preference
//        {
//            $new = true;
//            $preference = new Hobby();
//            $preference->setHobby($this->getUser());//adding a category for the connected user
//        } else { // edit preference
//            $new = false;
//            $preference = $em->find('AppBundle:Hobby', $id);
//            
//            if (is_null($preference)) { // if the requested id has no correspondance in DB : redirection on preferences' list
//                return $this->redirectToRoute('app_user_preference_list');
//            }
//        }
//    
//        $form = $this->createForm(HobbyType::class, $preference);
//        $form->handleRequest($request);
//        
//        // if the form has been submitted
//        if ($form->isSubmitted()) {
//            if ($form->isValid()) {
//                $em->persist($preference);
//                $em->flush();
//                
//                $msg = ($new)
//                    ? "Your hobby has been added to your profile."
//                    : "Changes made to your hobby have been saved."
//                ;
//                
//                $this->addFlash('success', $msg);
//                
//                return $this->redirectToRoute('app_user_preference_list');
//            } else {
//                $this->addFlash('error', 'The submitted data is not valid.');
//            }
//        }
//
//        return $this->render(
//            'AppBundle:User\Preference:edit.html.twig', array
//            (
//                'new'   =>  $new,
//                'form'  =>  $form->createView(),
//        ));
//    }

}

src/AppBundle/Controller/User/ReservationController.php
<?php

namespace AppBundle\Controller\User;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use AppBundle\Entity\Reservation;
use AppBundle\Entity\DetailReservation;

/**
 * Reservation controller
 * @Route("/reservation")
 */
class ReservationController extends Controller {

	/**
	 * @Route("/list")
	 */
	public function listAction() {
		
		$user = $this->getUser();
		$em=$this->getDoctrine()->getManager();
		$reservations = $em->getRepository('AppBundle:Reservation')->findByUser($user);
		
		$totalAmount=0;
		foreach ($reservations as $reservation) {
			foreach ($reservation->getDetailsReservations() as $d_reservation) {
				$d_reservation->setTotalPrice();
				$totalAmount=$reservation->getTotalAmount();
			}
		}
		
		return $this->render(
			'User/Reservation/list.html.twig',
			[
			  'reservations'	=>$reservations,
			  'user'		=>$user,
			  'totalAmount'	=>$totalAmount
			]
		);
	}

	/**
	 * @param $id
	 * @Route("/view/{id}")
	 */
	public function viewAction($id) {
		
		$user = $this->getUser();
		$em=$this->getDoctrine()->getManager();
		
		$reservation_detail=$em->getRepository('AppBundle:DetailReservation')->find($id);
		
		if (is_null($reservation_detail)){
			throw $this->createNotFoundException();
		}
		
		
		if($reservation_detail->getReservation()->getUser()->getId()!==$user->getId()){
			return $this->redirectToRoute('app_user_reservation_list');
		}

		return $this->render(
			'User/Reservation/view.html.twig',
			[
			  'd_reservation'	=>$reservation_detail,
			]
		);
	}
}

src/AppBundle/Tests/Controller/User/PreferenceControllerTest.php
<?php

namespace AppBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class User\PreferenceControllerTest extends WebTestCase
{
    public function testList()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', 'preference/list');
    }

    public function testEdit()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', 'preference/edit');
    }

    public function testAdd()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', 'preference/add');
    }

    public function testDelete()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', 'preference/delete');
    }

}

src/AppBundle/Resources/views/User/Preference/add.html.twig
{% extends "::base.html.twig" %}

{% block title %}AppBundle:User\Preference:add{% endblock %}

{% block body %}
<h1>Welcome to the User\Preference:add page</h1>
{% endblock %}

src/AppBundle/Resources/views/User/Preference/delete.html.twig
{% extends "::base.html.twig" %}

{% block title %}AppBundle:User\Preference:delete{% endblock %}

{% block body %}
<h1>Welcome to the User\Preference:delete page</h1>
{% endblock %}

src/AppBundle/Resources/views/User/Preference/edit.html.twig
{% extends "::base.html.twig" %}

{% block title %}AppBundle:User\Preference:edit{% endblock %}

{% block body %}
<h1>Welcome to the User\Preference:edit page</h1>
{% endblock %}

src/AppBundle/Resources/views/User/Preference/list.html.twig
{% extends "::product.html.twig" %}
{% block title %}Blue Sheep{% endblock %}

{% block content %}

{% block page_title %} <h1>Hobbies</h1>  {% endblock %}

{# bloc displaying messages flash with bootstrap style #}
{#    {% for label, flashes in app.session.flashbag.all %}
        {% for flash in flashes %} 
            {% if label == 'error' %} {% set label = 'danger' %} {% endif %}
           <div class='alert alert-{{ label }}'>
                {{ flash }}
            </div>
        {% endfor %}
    {% endfor %}#}
    
    {#{{ dump(preferences) }}#}
    
    <div class="row">
        
        {% if preferences %}
        <div class="col-sm-9">
        <div class="row">
        {% for preference in preferences %}
            <div class="col-sm-4">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ preference.category.name }}</h3>
                    </div>
                    <div class="panel-body">
                        <img class="img-responsive portfolio-item" src="{{ asset('img/cat/'~ preference.category.photo) }}" alt="">
                        <p><strong>Votre note :</strong></p>
                        {% for i in 1 .. preference.note%}
                            <span class="fa fa-star fa-lg" aria-hidden="true"></span>
                        {% endfor %}
                        &nbsp
                        <p>
                            <a href='{{ path('app_user_preference_edit', {"id": preference.id}) }}' class='btn btn-default'>
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Modifier">  </span>
                            </a>
                            <a href='{{ path('app_user_preference_delete', {"id":preference.id}) }}' class='btn btn-primary'>
                            <span class="glyphicon glyphicon-remove" aria-hidden="true" title="Supprimer">  </span>
                            </a>
                            <a></a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    {% endif %}
        
        <div class="col-sm-3 well well-lg">
        {{ form_start(form, {'action': path('app_user_preference_add'), 'method': 'POST'}) }}
        <h3>Ajouter un hobby</h3>
        {{ form_row(form.category) }}
        {{ form_row(form.note) }}
        <span class="form-btn-group">
            <button type="submit" class="btn btn-primary btn-block">
                <span class="glyphicon glyphicon-star" aria-hidden="true" title="Add">  Ajouter </span>
            </button>
            <button class="btn btn-info btn-block">
                <input type="reset" value="reset" hidden="true" /><span class="glyphicon glyphicon-star-empty" aria-hidden="true" title="Cancel"> Annuler </span>
            </button>    
        
        </span>
        {{ form_end(form) }}
        </div>
    </div>

{% endblock %}